import {chromium} from 'playwright';
import {createWebProductServer} from '../dist/src/web/server.js';
import {once} from 'node:events';
import {mkdir} from 'node:fs/promises';
const server=createWebProductServer();
server.listen(0,'127.0.0.1');
await once(server,'listening');
await mkdir('docs/evidence/educ6192',{recursive:true});
import assert from 'node:assert/strict';
const browser=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE_PATH,headless:true,args:['--no-sandbox','--disable-dev-shm-usage','--disable-gpu']});
try {
const page=await browser.newPage({viewport:{width:1440,height:1050}});let errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto(`http://127.0.0.1:${server.address().port}`);
await page.locator('#generate:not([disabled])').waitFor();
assert(await page.locator('#prompt').getAttribute('readonly')!==null);
assert(await page.locator('[data-mode=live]').isDisabled());
await page.screenshot({path:'docs/evidence/educ6192/v2-home.png',fullPage:true});
await page.locator('#generate').click();
await page.waitForFunction(()=>document.querySelector('#run-state').textContent==='Complete',{},{timeout:30000});
const game=page.frameLocator('#preview-frame');
assert.equal(await game.locator('#player-energy').textContent(),'3');
assert.equal(await game.locator('#enemy-hp').textContent(),'20');
await game.locator('#check-prediction').click();
assert.match(await game.locator('#prediction-feedback').textContent(),/whole number/);
await game.locator('#prediction').fill('0');await game.locator('#check-prediction').click();
assert.match(await game.locator('#prediction-feedback').textContent(),/Not quite/);
await game.locator('#prediction').fill('2');await game.locator('#check-prediction').click();
assert.match(await game.locator('#prediction-feedback').textContent(),/Correct/);
for(let i=0;i<3;i++)await game.locator('#strike-button').click();
assert(await game.locator('#strike-button').isDisabled());
assert.equal(await game.locator('#enemy-hp').textContent(),'2');
await page.locator('.left-panel').evaluate(e=>e.scrollTop=0);
await page.screenshot({path:'docs/evidence/educ6192/v2-complete.png',fullPage:true});
await game.locator('#restart-button').click();assert.equal(await game.locator('#player-energy').textContent(),'3');
await game.locator('#prediction').focus();await page.keyboard.type('2');await page.keyboard.press('Tab');await page.keyboard.press('Enter');assert.match(await game.locator('#prediction-feedback').textContent(),/Correct/);
const downloadPromise=page.waitForEvent('download');await page.locator('#download').click();const download=await downloadPromise;assert.equal(await download.failure(),null);
await page.setViewportSize({width:390,height:844});
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
assert.equal(await game.locator('html').evaluate(e=>e.scrollWidth<=window.innerWidth),true);
await page.locator('#preview-frame').scrollIntoViewIfNeeded();
await game.locator('#strike-button').scrollIntoViewIfNeeded();
await page.screenshot({path:'docs/evidence/educ6192/v2-mobile.png'});
assert.deepEqual(errors,[]);
console.log('PASS: browser build/evaluation, untouched initial state, missing/wrong/correct prediction, 3 strikes and resource boundary, restart, keyboard check, ZIP download, desktop/mobile overflow, no page errors.');
} finally { await browser.close(); server.closeAllConnections(); await new Promise(resolve=>server.close(resolve)); }
